// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfvLc3h0JkhA8PzQkZJS6JG5Nrkq3PwDk',
    appId: '1:466897115771:web:e0e614bfba5eb4a801e0de',
    messagingSenderId: '466897115771',
    projectId: 'khwater-fa3b8',
    authDomain: 'khwater-fa3b8.firebaseapp.com',
    storageBucket: 'khwater-fa3b8.appspot.com',
    measurementId: 'G-TG5GHYVMGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaTe5l7BklhYcH9_8KRG-qfMihm99q07c',
    appId: '1:466897115771:android:efe5d2fade4db6ba01e0de',
    messagingSenderId: '466897115771',
    projectId: 'khwater-fa3b8',
    storageBucket: 'khwater-fa3b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq2aWNoXmrTKic1PUXJqVfypHW-exT90Q',
    appId: '1:466897115771:ios:dd0c881d87e2f1bd01e0de',
    messagingSenderId: '466897115771',
    projectId: 'khwater-fa3b8',
    storageBucket: 'khwater-fa3b8.appspot.com',
    iosBundleId: 'com.example.khwater',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq2aWNoXmrTKic1PUXJqVfypHW-exT90Q',
    appId: '1:466897115771:ios:43163c28ef0c63f301e0de',
    messagingSenderId: '466897115771',
    projectId: 'khwater-fa3b8',
    storageBucket: 'khwater-fa3b8.appspot.com',
    iosBundleId: 'com.example.khwater.RunnerTests',
  );
}
